require:
  - rubocop-rspec
AllCops:
  DisplayCopNames: true
  NewCops: enable
  TargetRubyVersion: 3.1
Style/Documentation:
  Enabled: false
Style/EndOfLine:
  Enabled: false
Style/OptionalBooleanParameter:
  Enabled: false
Metrics/MethodLength:
  Max: 18
Metrics/BlockLength:
  Max: 40
Gemspec/DevelopmentDependencies:
  Enabled: false
RSpec/MultipleExpectations:
  Enabled: false
RSpec/ExampleLength:
  Max: 30
Layout/LineLength:
  Exclude: 
    - spec/quelink_mg/resp/*_spec.rb
    - spec/quelink_mg/gl30meu/**/*_spec.rb
    - spec/quelink_mg/**.rb
